source 'https://rubygems.org'

gem 'selenium-webdriver', '4.3.0'
gem 'watir'
gem 'watir-get-image-content'
gem 'two_captcha'
gem 'telegram-bot-ruby'
gem 'mini_magick'
gem 'pry'
gem 'mini_magick'
gem 'image_processing', '~> 1.0'
gem 'faraday'